name: Flutter Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # Latest Flutter version eka use karanna kiyanawa
          channel: 'stable'
          flutter-version: '3.29.0' 
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Kalin error eka ena path eka clear karanna
      - name: Clean Project
        run: flutter clean

      # Android build settings update karanna meka udaw wenawa
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }} # Java version eka fix karanna

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
